# -*- coding: utf-8 -*-
"""Lab2_david setondo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdZAMQA5P1kSD1fJUYXnujV0ntLyjJAx
"""

import pandas as pd


df = pd.read_csv("oceny.csv", sep=";")

print(df)

df["srednia"] = df.iloc[:, 1:].mean(axis=1)

print(df[["uczen", "srednia"]])

najlepszy = df.loc[df["srednia"].idxmax()]

print("Najlepszy uczeń:", najlepszy["uczen"])
print("Średnia:", najlepszy["srednia"])

import pandas as pd

def oblicz_srednia(oceny):
    """Calculate arithmetic mean of grades"""
    return sum(oceny) / len(oceny)


def wczytaj_dane(plik):
    """Load CSV file"""
    return pd.read_csv(plik, sep=";")


df = wczytaj_dane("oceny.csv")

df["srednia"] = df.iloc[:, 1:].apply(lambda x: oblicz_srednia(x), axis=1)

print(df[["uczen", "srednia"]])

najlepszy = df.loc[df["srednia"].idxmax()]

print("\nNajlepszy uczeń:", najlepszy["uczen"])
print("Średnia:", najlepszy["srednia"])

# test jednostkowy
def test_oblicz_srednia():
    oceny = [4, 4, 4, 4]
    wynik = oblicz_srednia(oceny)
    assert wynik == 4


test_oblicz_srednia()
print("\nTest OK")